package gui;

import com.mxgraph.layout.mxOrganicLayout;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.view.mxGraph;
import models.Conexion;
import models.Equipo;

import java.awt.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJP = new javax.swing.JPanel();
        upperMenu = new javax.swing.JPanel();
        titleLB = new javax.swing.JLabel();
        euiposOptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonsJP = new javax.swing.JPanel();
        agregarEquipoBT = new javax.swing.JButton();
        modificarEquipoBT = new javax.swing.JButton();
        eliminarEquipoBT = new javax.swing.JButton();
        conexionesOptionsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonsJP1 = new javax.swing.JPanel();
        agregarConexionBT = new javax.swing.JButton();
        modificarConexionBT = new javax.swing.JButton();
        eliminarConexionBT = new javax.swing.JButton();
        lowerMenu = new javax.swing.JPanel();
        tracerouteBT = new javax.swing.JButton();
        pingBT = new javax.swing.JButton();
        statusMapBT = new javax.swing.JButton();
        problemasBT = new javax.swing.JButton();
        graphJP = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        menuJP.setMinimumSize(new java.awt.Dimension(0, 400));
        menuJP.setPreferredSize(new java.awt.Dimension(300, 600));
        menuJP.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        upperMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        upperMenu.setLayout(new java.awt.GridLayout(3, 1));

        titleLB.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        titleLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB.setText("Red Lan Computadoras");
        upperMenu.add(titleLB);

        euiposOptionsPanel.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipos");
        euiposOptionsPanel.add(jLabel1);

        buttonsJP.setLayout(new java.awt.GridLayout(1, 3, 3, 0));

        agregarEquipoBT.setText("Agregar");
        agregarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarEquipoBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        agregarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(agregarEquipoBT);

        modificarEquipoBT.setText("Modificar ");
        modificarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(modificarEquipoBT);

        eliminarEquipoBT.setText("Eliminar ");
        eliminarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(eliminarEquipoBT);

        euiposOptionsPanel.add(buttonsJP);

        upperMenu.add(euiposOptionsPanel);

        conexionesOptionsPanel.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conexiones");
        conexionesOptionsPanel.add(jLabel2);

        buttonsJP1.setLayout(new java.awt.GridLayout(1, 3, 3, 0));

        agregarConexionBT.setText("Agregar");
        agregarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarConexionBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        agregarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(agregarConexionBT);

        modificarConexionBT.setText("Modificar ");
        modificarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(modificarConexionBT);

        eliminarConexionBT.setText("Eliminar ");
        eliminarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(eliminarConexionBT);

        conexionesOptionsPanel.add(buttonsJP1);

        upperMenu.add(conexionesOptionsPanel);

        menuJP.add(upperMenu);

        lowerMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        lowerMenu.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        tracerouteBT.setText("Ruta entre Equipos");
        tracerouteBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tracerouteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracerouteBTActionPerformed(evt);
            }
        });
        lowerMenu.add(tracerouteBT);

        pingBT.setText("Ping Equipo");
        pingBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pingBTActionPerformed(evt);
            }
        });
        lowerMenu.add(pingBT);

        statusMapBT.setText("Mapa de estado equipos");
        statusMapBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusMapBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusMapBTActionPerformed(evt);
            }
        });
        lowerMenu.add(statusMapBT);

        problemasBT.setText("Problemas Conectividad");
        problemasBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        problemasBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemasBTActionPerformed(evt);
            }
        });
        lowerMenu.add(problemasBT);

        menuJP.add(lowerMenu);

        graphJP.setPreferredSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout graphJPLayout = new javax.swing.GroupLayout(graphJP);
        graphJP.setLayout(graphJPLayout);
        graphJPLayout.setHorizontalGroup(
            graphJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        graphJPLayout.setVerticalGroup(
            graphJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graphJP, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEquipoBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarEquipoBTActionPerformed

    private void modificarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEquipoBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarEquipoBTActionPerformed

    private void eliminarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEquipoBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarEquipoBTActionPerformed

    private void agregarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarConexionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarConexionBTActionPerformed

    private void modificarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarConexionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarConexionBTActionPerformed

    private void eliminarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarConexionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarConexionBTActionPerformed

    private void tracerouteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracerouteBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracerouteBTActionPerformed

    private void pingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pingBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pingBTActionPerformed

    private void statusMapBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusMapBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusMapBTActionPerformed

    private void problemasBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemasBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemasBTActionPerformed

    protected void visualizeGraph(List<Equipo> equipos, List<Conexion> conexiones) {
        mxGraph mxGraph = new mxGraph() {
            @Override
            public boolean isCellConnectable(Object cell) {
                return false; // Deshabilitar la creación de nuevas aristas
            }

            @Override
            public boolean isCellMovable(Object cell) {
                return !getModel().isEdge(cell); // Permitir mover solo los vértices
            }
        };
        Object parent = mxGraph.getDefaultParent();

        mxGraph.getModel().beginUpdate();
        try {
            Map<Equipo, Object> vertexMap = new HashMap<>();
            for (Equipo equipo : equipos) {
                Object v = mxGraph.insertVertex(parent, null, equipo.getCodigo(), 0, 0, 40, 30);
                vertexMap.put(equipo, v);
            }
            for (Conexion conexion : conexiones) {
                Equipo source = conexion.getEquipo1();
                Equipo target = conexion.getEquipo2();
                String edgeStyle = "endArrow=none";
                mxGraph.insertEdge(parent, null, conexion.getTipoCable().getVelocidad(), vertexMap.get(source), vertexMap.get(target), edgeStyle);
            }
        } finally {
            mxGraph.getModel().endUpdate();
        }

        mxOrganicLayout layout = new mxOrganicLayout(mxGraph);
        layout.execute(mxGraph.getDefaultParent());

        mxGraphComponent graphComponent = new mxGraphComponent(mxGraph);
        graphComponent.setConnectable(false); // Deshabilitar la conexión de nuevos arcos
        graphComponent.zoomAndCenter(); // Centrar y ajustar el zoom del grafo

        graphJP.setLayout(new BorderLayout()); // Asegúrate de que el LayoutManager sea BorderLayout
        graphJP.removeAll();
        graphJP.add(graphComponent, BorderLayout.CENTER);
        graphJP.revalidate();
        graphJP.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarConexionBT;
    private javax.swing.JButton agregarEquipoBT;
    private javax.swing.JPanel buttonsJP;
    private javax.swing.JPanel buttonsJP1;
    private javax.swing.JPanel conexionesOptionsPanel;
    private javax.swing.JButton eliminarConexionBT;
    private javax.swing.JButton eliminarEquipoBT;
    private javax.swing.JPanel euiposOptionsPanel;
    private javax.swing.JPanel graphJP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lowerMenu;
    private javax.swing.JPanel menuJP;
    private javax.swing.JButton modificarConexionBT;
    private javax.swing.JButton modificarEquipoBT;
    private javax.swing.JButton pingBT;
    private javax.swing.JButton problemasBT;
    private javax.swing.JButton statusMapBT;
    private javax.swing.JLabel titleLB;
    private javax.swing.JButton tracerouteBT;
    private javax.swing.JPanel upperMenu;
    // End of variables declaration//GEN-END:variables
}
