package gui;

import com.mxgraph.layout.hierarchical.mxHierarchicalLayout;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.view.mxGraph;
import models.Conexion;
import models.Equipo;
import models.TipoCable;

import java.awt.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MainPanel extends javax.swing.JPanel {
    private static final String VERTEX_STYLE = "fontColor=white;strokeColor=black;fillColor=";
    private static final String EDGE_STYLE = "endArrow=none;strokeColor=";
    private static final int VERTEX_WIDTH = 40;
    private static final int VERTEX_HEIGHT = 30;

    private mxGraph mxGraph;
    Map<Equipo, Object> vertexMap;


    /**
     * Creates new form MainJPanel
     */
    public MainPanel() {
        initComponents();
        initMxGraphStyle();
    }

    private void initMxGraphStyle() {
        mxGraph = new mxGraph() {
            @Override
            public boolean isCellConnectable(Object cell) {
                return false; // Deshabilitar la creación de nuevas aristas
            }

            @Override
            public boolean isCellMovable(Object cell) {
                return !getModel().isEdge(cell); // Permitir mover solo los vértices
            }
        };
        vertexMap = new HashMap<>();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJP = new javax.swing.JPanel();
        upperMenu = new javax.swing.JPanel();
        titleLB = new javax.swing.JLabel();
        euiposOptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonsJP = new javax.swing.JPanel();
        agregarEquipoBT = new javax.swing.JButton();
        modificarEquipoBT = new javax.swing.JButton();
        eliminarEquipoBT = new javax.swing.JButton();
        conexionesOptionsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonsJP1 = new javax.swing.JPanel();
        agregarConexionBT = new javax.swing.JButton();
        modificarConexionBT = new javax.swing.JButton();
        eliminarConexionBT = new javax.swing.JButton();
        lowerMenu = new javax.swing.JPanel();
        tracerouteBT = new javax.swing.JButton();
        pingBT = new javax.swing.JButton();
        statusMapBT = new javax.swing.JButton();
        problemasBT = new javax.swing.JButton();
        graphJP = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        menuJP.setMinimumSize(new java.awt.Dimension(0, 400));
        menuJP.setPreferredSize(new java.awt.Dimension(300, 600));
        menuJP.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        upperMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        upperMenu.setLayout(new java.awt.GridLayout(3, 1));

        titleLB.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        titleLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLB.setText("Red Lan Computadoras");
        upperMenu.add(titleLB);

        euiposOptionsPanel.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipos");
        euiposOptionsPanel.add(jLabel1);

        buttonsJP.setLayout(new java.awt.GridLayout(1, 3, 3, 0));

        agregarEquipoBT.setText("Agregar");
        agregarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarEquipoBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        agregarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(agregarEquipoBT);

        modificarEquipoBT.setText("Modificar ");
        modificarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(modificarEquipoBT);

        eliminarEquipoBT.setText("Eliminar ");
        eliminarEquipoBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarEquipoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEquipoBTActionPerformed(evt);
            }
        });
        buttonsJP.add(eliminarEquipoBT);

        euiposOptionsPanel.add(buttonsJP);

        upperMenu.add(euiposOptionsPanel);

        conexionesOptionsPanel.setLayout(new java.awt.GridLayout(2, 1, 3, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conexiones");
        conexionesOptionsPanel.add(jLabel2);

        buttonsJP1.setLayout(new java.awt.GridLayout(1, 3, 3, 0));

        agregarConexionBT.setText("Agregar");
        agregarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarConexionBT.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        agregarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(agregarConexionBT);

        modificarConexionBT.setText("Modificar ");
        modificarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(modificarConexionBT);

        eliminarConexionBT.setText("Eliminar ");
        eliminarConexionBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarConexionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarConexionBTActionPerformed(evt);
            }
        });
        buttonsJP1.add(eliminarConexionBT);

        conexionesOptionsPanel.add(buttonsJP1);

        upperMenu.add(conexionesOptionsPanel);

        menuJP.add(upperMenu);

        lowerMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 5, 5));
        lowerMenu.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        tracerouteBT.setText("Ruta entre Equipos");
        tracerouteBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tracerouteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracerouteBTActionPerformed(evt);
            }
        });
        lowerMenu.add(tracerouteBT);

        pingBT.setText("Ping Equipo");
        pingBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pingBTActionPerformed(evt);
            }
        });
        lowerMenu.add(pingBT);

        statusMapBT.setText("Mapa de estado equipos");
        statusMapBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusMapBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusMapBTActionPerformed(evt);
            }
        });
        lowerMenu.add(statusMapBT);

        problemasBT.setText("Problemas Conectividad");
        problemasBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        problemasBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemasBTActionPerformed(evt);
            }
        });
        lowerMenu.add(problemasBT);

        menuJP.add(lowerMenu);

        graphJP.setPreferredSize(new java.awt.Dimension(500, 600));
        graphJP.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(graphJP, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(graphJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEquipoBTActionPerformed
        // TODO add your handling code here:
        //DEBUG
        Equipo equipo = vertexMap.keySet().iterator().next();
        equipo.setCodigo("Equipo Test");
        System.out.println(equipo.getCodigo());
        addVisualVertex(equipo);
    }//GEN-LAST:event_agregarEquipoBTActionPerformed

    private void modificarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEquipoBTActionPerformed
        // TODO add your handling code here:
        //DEBUG
        Equipo modificado = null;
        for (Equipo equipo : vertexMap.keySet()) {
            if (equipo.getCodigo().equals("SW04")) {
                modificado = equipo;
                break;
            }
        }
        modificado.setEstado(!modificado.isEstado());
        modifyVisualVertex(modificado);
    }//GEN-LAST:event_modificarEquipoBTActionPerformed

    private void eliminarEquipoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEquipoBTActionPerformed
        // TODO add your handling code here:
        Equipo modificado = null;
        for (Equipo equipo : vertexMap.keySet()) {
            if (equipo.getCodigo().equals("SW04")) {
                modificado = equipo;
                break;
            }
        }
        removeVisualVertex(modificado);
    }//GEN-LAST:event_eliminarEquipoBTActionPerformed

    private void agregarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarConexionBTActionPerformed
        // TODO add your handling code here:
        //DEBUG
        Equipo e1 = null;
        Equipo e2 = null;
        for (Equipo equipo : vertexMap.keySet()) {
            if (equipo.getCodigo().equals("SWAP")) {
                e1 = equipo;
            }
            if (equipo.getCodigo().equals("AP03")) {
                e2 = equipo;
            }
        }
        Conexion conexion = new Conexion(new TipoCable("T", "Cable Test", 10), e1, e1.getPuertos().getFirst().getTipoPuerto(), e2, e2.getPuertos().getFirst().getTipoPuerto());
        addVisualEdge(conexion);
    }//GEN-LAST:event_agregarConexionBTActionPerformed

    private void modificarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarConexionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarConexionBTActionPerformed

    private void eliminarConexionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarConexionBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarConexionBTActionPerformed

    private void tracerouteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracerouteBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracerouteBTActionPerformed

    private void pingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pingBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pingBTActionPerformed

    private void statusMapBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusMapBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusMapBTActionPerformed

    private void problemasBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemasBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemasBTActionPerformed

    /**
     * Visualizes the graph by adding vertices and edges, and applying a hierarchical layout.
     *
     * @param equipos    List of Equipo objects representing the vertices of the graph.
     * @param conexiones List of Conexion objects representing the edges of the graph.
     */
    protected void visualizeGraph(List<Equipo> equipos, List<Conexion> conexiones) {

        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Insert vertices for each Equipo object
            for (Equipo equipo : equipos) {
                insertColoredVertex(equipo);
            }
            // Insert edges for each Conexion object
            for (Conexion conexion : conexiones) {
                insertColoredEdge(conexion.getEquipo1(), conexion.getEquipo2(), conexion);
            }
        } finally {
            // End updating the graph model
            mxGraph.getModel().endUpdate();
        }

        // Apply a hierarchical layout to the graph
        mxHierarchicalLayout layout = new mxHierarchicalLayout(mxGraph);
        layout.execute(mxGraph.getDefaultParent());

        // Create a graph component to display the graph
        mxGraphComponent graphComponent = new mxGraphComponent(mxGraph);
        graphComponent.setSize(graphJP.getSize()); // Set the size of the graph component to match the panel
        graphComponent.setConnectable(false); // Disable connecting new edges
        graphComponent.zoomAndCenter(); // Center and zoom the graph

        // Add the graph component to the panel
        graphJP.removeAll();
        graphJP.add(graphComponent, BorderLayout.CENTER);
        graphJP.revalidate();
        graphJP.repaint();
    }

    /**
     * Adds a visual representation of a vertex to the graph.
     *
     * @param equipo The Equipo object representing the vertex to be added.
     */
    public void addVisualVertex(Equipo equipo) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Insert the vertex with the specified color
            insertColoredVertex(equipo);
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Removes a visual representation of a vertex from the graph.
     *
     * @param equipo The Equipo object representing the vertex to be removed.
     */
    public void removeVisualVertex(Equipo equipo) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Get the vertex associated with the Equipo object
            Object v = vertexMap.get(equipo);

            // Remove all edges connected to the vertex
            Object[] edges = mxGraph.getEdges(v);
            for (Object edge : edges) {
                mxGraph.getModel().remove(edge);
            }

            // Remove the vertex from the graph model
            mxGraph.getModel().remove(v);

            // Remove the vertex from the vertex map
            vertexMap.remove(equipo);
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Modifies the visual representation of a vertex in the graph.
     *
     * @param equipo The Equipo object representing the vertex to be modified.
     */
    public void modifyVisualVertex(Equipo equipo) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Get the vertex associated with the Equipo object
            Object v = vertexMap.get(equipo);

            // Set the vertex style based on the estado of the Equipo
            if (equipo.isEstado()) {
                mxGraph.getModel().setStyle(v, VERTEX_STYLE + "green");
            } else {
                mxGraph.getModel().setStyle(v, VERTEX_STYLE + "red");
            }

            // Get all edges connected to the vertex and set their style based on the estado of the Equipo
            Object[] edges = mxGraph.getEdges(v);
            for (Object edge : edges) {
                if (equipo.isEstado()) {
                    mxGraph.getModel().setStyle(edge, EDGE_STYLE + "green");
                } else {
                    mxGraph.getModel().setStyle(edge, EDGE_STYLE + "red");
                }
            }

            // Update the vertex value with the codigo of the Equipo
            mxGraph.getModel().setValue(v, equipo.getCodigo());
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Adds a visual representation of an edge to the graph.
     *
     * @param conexion The Conexion object representing the edge to be added.
     */
    public void addVisualEdge(Conexion conexion) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Insert the edge with the specified color
            insertColoredEdge(conexion.getEquipo1(), conexion.getEquipo2(), conexion);
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Inserts a colored vertex into the graph.
     *
     * @param equipo The Equipo object representing the vertex to be added.
     */
    private void insertColoredVertex(Equipo equipo) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Determine the fill color based on the estado of the Equipo
        String fillColor;
        if (equipo.isEstado()) {
            fillColor = "green";
        } else {
            fillColor = "red";
        }

        // Insert the vertex with the specified color and dimensions
        Object v = mxGraph.insertVertex(parent, null, equipo.getCodigo(), 0, 0, VERTEX_WIDTH, VERTEX_HEIGHT, VERTEX_STYLE + fillColor);

        // Map the Equipo object to the inserted vertex
        vertexMap.put(equipo, v);
    }

    /**
     * Removes a visual representation of an edge from the graph.
     *
     * @param conexion The Conexion object representing the edge to be removed.
     */
    public void removeVisualEdge(Conexion conexion) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Get the source and target vertices associated with the Conexion object
            Equipo source = conexion.getEquipo1();
            Equipo target = conexion.getEquipo2();

            // Get the edge between the source and target vertices
            Object edge = mxGraph.getEdgesBetween(vertexMap.get(source), vertexMap.get(target))[0];

            // Remove the edge from the graph model
            mxGraph.getModel().remove(edge);
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Modifies the visual representation of an edge in the graph.
     *
     * @param conexion The Conexion object representing the edge to be modified.
     */
    public void modifyVisualEdge(Conexion conexion) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Begin updating the graph model
        mxGraph.getModel().beginUpdate();
        try {
            // Get the source and target vertices associated with the Conexion object
            Equipo source = conexion.getEquipo1();
            Equipo target = conexion.getEquipo2();

            // Get the edge between the source and target vertices
            Object edge = mxGraph.getEdgesBetween(vertexMap.get(source), vertexMap.get(target))[0];

            // Update the edge value with the velocidad of the TipoCable
            mxGraph.getModel().setValue(edge, conexion.getTipoCable().getVelocidad());
        } finally {
            // End updating the graph model and repaint the panel
            mxGraph.getModel().endUpdate();
            graphJP.repaint();
        }
    }

    /**
     * Inserts a colored edge into the graph.
     *
     * @param source   The source Equipo object representing the starting vertex of the edge.
     * @param target   The target Equipo object representing the ending vertex of the edge.
     * @param conexion The Conexion object representing the edge to be added.
     */
    private void insertColoredEdge(Equipo source, Equipo target, Conexion conexion) {
        // Get the default parent for the graph
        Object parent = mxGraph.getDefaultParent();

        // Determine the stroke color based on the estado of the source and target Equipos
        String strokeColor;
        if (source.isEstado() && target.isEstado()) {
            strokeColor = "green";
        } else {
            strokeColor = "red";
        }

        // Insert the edge with the specified color and velocidad
        mxGraph.insertEdge(parent, null, conexion.getTipoCable().getVelocidad(), vertexMap.get(source), vertexMap.get(target), EDGE_STYLE + strokeColor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarConexionBT;
    private javax.swing.JButton agregarEquipoBT;
    private javax.swing.JPanel buttonsJP;
    private javax.swing.JPanel buttonsJP1;
    private javax.swing.JPanel conexionesOptionsPanel;
    private javax.swing.JButton eliminarConexionBT;
    private javax.swing.JButton eliminarEquipoBT;
    private javax.swing.JPanel euiposOptionsPanel;
    private javax.swing.JPanel graphJP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel lowerMenu;
    private javax.swing.JPanel menuJP;
    private javax.swing.JButton modificarConexionBT;
    private javax.swing.JButton modificarEquipoBT;
    private javax.swing.JButton pingBT;
    private javax.swing.JButton problemasBT;
    private javax.swing.JButton statusMapBT;
    private javax.swing.JLabel titleLB;
    private javax.swing.JButton tracerouteBT;
    private javax.swing.JPanel upperMenu;
    // End of variables declaration//GEN-END:variables
}
